apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-daxv
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:c53c18a4bb45136723073af8042f650c1dc0dfe6f42c9e4b82d4f2607e9ac8c7
        name: my-nodejs
        resources: {}
status: {}
