apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-mt0x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-mt0x
    app.kubernetes.io/part-of: test-application
  name: governance-policy-propagah6kc
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: governance-policy-propagator-mt0x
    weight: 100
status: {}
