apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-mt0x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-mt0x
    app.kubernetes.io/part-of: test-application
  name: governance-policy-propagator-mt0x
  namespace: karthik-jk-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: governance-policy-propagator-mt0x
status:
  loadBalancer: {}
